#!/usr/bin/env fish

set -l msg_file $argv[1]

# read fist line in commit msg
set -l commit_title (head -n 1 $msg_file)

# star 'codex' or 'codex:'  check
if string match -ri '^codex' $commit_title
    echo "🤖 [Codex Commit Detected] start verify scripts"
    
    ~/agent-tools/hooks/verify.fish
    set -l exit_code $status

    if test $exit_code -ne 0
        echo "❌ [Rejected] 검증에 실패하여 커밋을 중단합니다."
        exit 1
    end
else
    echo "commit을 진행합니다."
    exit 0
end
